Django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lab1/', include('lab1.urls', namespace='lab1')),
    path('lab2/', include('lab2.urls', namespace='lab2')),
    path('lab4/', include('lab4.urls', namespace='lab4'))

]

lab1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from lab1 import views

app_name = 'lab1'
urlpatterns = [
    path('', views.index, name='index'),
    path('get_more_tables', views.get_more_tables, name='tables')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lab2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from lab2 import views

app_name = 'lab2'
urlpatterns = [
    path('', views.index, name='index'),
    path('weather', views.weather, name='weather')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lab4/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from lab4 import views

app_name = 'lab4'
urlpatterns = [
    path('', views.index, name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lab1/models.py
# Create your models here.

from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

lab2/models.py
# Create your models here.

from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

lab4/models.py
from django.db import models

# Create your models here.

lab1/views.py
from django.shortcuts import render
import json
from lab1.linkcheck import select_5_from_json
from Django.settings import BASE_DIR


# Create your views here.
def index(request):
    print("base dir path", BASE_DIR)

    return render(request, 'lab1/lab1.html')


def get_more_tables(request):
    increment = int(request.GET['append_increment'])
    increment_int = increment + 1
    data = json.load(open(BASE_DIR + '/lab1/media/TwitterTweets17.json'))
    context = select_5_from_json(increment_int, data)

    return render(request, 'lab1/get_more_tables.html', {"context": context})

lab2/views.py
# Create your views here.
from pprint import pprint

from django.shortcuts import render

from lab2 import GetWeather_Data
from lab2.GetWeather_Data import CitySearchError


def index(request):
    return render(request, "lab2/lab2.html")


def weather(request):
    latitude = request.GET['latitude']
    longitude = request.GET['longitude']
    try:
        data = GetWeather_Data.from_lat_long(latitude, longitude)
        pprint(data)
    except CitySearchError as e:
        data = None
        print(e.message)

    return render(request, "lab2/weather.html", {'data': data})

lab4/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, 'lab4/lab4.html')

templates/lab1/get_more_tables.html
{% load static %}
{% for message in context %}
  <li class="collection-item avatar">
    <img src="{{ message.icon }}" alt="" class="circle">
    <p>{{ message.text }} <br>
    </p>
    {#            <a href="#!" class="secondary-content"><i class="material-icons">grade</i></a>#}
  </li>
{% endfor %}

templates/lab1/lab1.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
  <meta charset="UTF-8">
  <title>Lab1</title>

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <!--Import materialize.css-->
  <link type="text/css" rel="stylesheet" href="{% static "materializecss/sass/materialize.css" %}"
        media="screen,projection"/>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

</head>
<body>
<nav>
  <div class="nav-wrapper">
    <p class="center-align" style="font-size: 30px">Lab 1</p>
  </div>
</nav>
<main>
  <div class="container">
    <div class="row">
      <div class="col s8 push-s2" style="margin-top: 10%">
        <ul class="collection col s12 z-depth-2" id="_appendHere">
        </ul>
      </div>
    </div>
  </div>
</main>

<!--Import jQuery before materialize.js-->
<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script type="text/javascript" src="{% static "materializecss/js/bin/materialize.min.js" %}"></script>

<script>
  $('main').hide();
  var append_increment = 0;
  $.ajax({
    type: "GET",
    url: "{% url 'lab1:tables' %}",  // URL to your view that serves new info
    data: {'append_increment': append_increment}
  })
      .done(function (response) {
        $('#_appendHere').html(response).fadeIn('slow', function () {
          $('main').show();
        });
        append_increment += 1;
      });

  $.fn.send_request = function () {
    $.ajax({
      type: "GET",
      url: "{% url 'lab1:tables' %}",  // URL to your view that serves new info
      data: {'append_increment': append_increment}
    })
        .done(function (response) {
          $('#_appendHere').fadeOut('slow', function () {
            $('#_appendHere').html(response).fadeIn('slow')
          });
          append_increment += 1;
        });
  };
  $.fn.send_request();

  setInterval(function () {
    $.fn.send_request();
  }, 5000)
</script>

</body>
</html>

templates/lab2/lab2.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Lab2</title>

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <!--Import materialize.css-->
  <link type="text/css" rel="stylesheet" href="{% static "materializecss/sass/materialize.css" %}"
        media="screen,projection"/>

  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
  <script type="text/javascript" src="{% static "materializecss/js/bin/materialize.min.js" %}"></script>


</head>
<body>
<nav>
  <div class="nav-wrapper">
    <p class="center-align" style="font-size: 30px; margin-top: 0">Lab 2 Weather API</p>
  </div>
</nav>
<main>
  <div class="container">
    <div class="row">
      <div class="col s8 push-s2" style="margin-top: 5%">
        <div class="card" id="_appendHere">
          <div class="card-image waves-effect waves-block waves-light">
            <img src="http://b1-q.mafengwo.net/s8/M00/02/BF/wKgBpVWnJL6AfCcFAA_oZSqEvVE56.jpeg?imageMogr2%2Fthumbnail%2F%21690x370r%2Fgravity%2FCenter%2Fcrop%2F%21690x370%2Fquality%2F100">
          </div>
          <div class="card-content">
                        <span class="card-title activator grey-text text-darken-4">Click right to see more<i
                                class="material-icons right">more_vert</i></span>
            <p><a href="#">Forecast</a></p>

          </div>
          <div class="card-reveal">
                        <span class="card-title grey-text text-darken-4">Weather<i
                                class="material-icons right">close</i></span>
            <p>No Data</p>
          </div>
        </div>

      </div>
      <div class="col s12 m6">
      </div>

    </div>
  </div>
</main>
<script>

  var latitude = 0;
  var longitude = 0;

  function getLocation() {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(showPosition);
    } else {
      alert("Geolocation is not supported by this browser.");
    }
  }

  function showPosition(position) {
    latitude = position.coords.latitude;
    longitude = position.coords.longitude;
    console.log(longitude);
    dataBackend();
  }

  function dataBackend() {
    $.ajax({
      type: "GET",
      url: "{% url 'lab2:weather' %}",  // URL to your view that serves new info
      data: {'latitude': latitude, 'longitude': longitude}
    })
        .done(function (response) {
          $('#_appendHere').replaceWith(response);
        });
  }

  getLocation();

</script>
</body>
</html>

templates/lab2/weather.html
{% load static %}
<div class="card">
  <div class="card-image waves-effect waves-block waves-light">
    <img src="http://b1-q.mafengwo.net/s8/M00/02/BF/wKgBpVWnJL6AfCcFAA_oZSqEvVE56.jpeg?imageMogr2%2Fthumbnail%2F%21690x370r%2Fgravity%2FCenter%2Fcrop%2F%21690x370%2Fquality%2F100">
  </div>
  <div class="card-content">
    <span class="card-title activator grey-text text-darken-4">{{ data.location }}
      <img src="{{ data.icon_url }}">
      {{ data.temperature }}
      <i class="material-icons right">more_vert</i></span>
    <p><a href="{{ data.forecast_url }}">Forecast</a></p>

  </div>
  <div class="card-reveal">
                        <span class="card-title grey-text text-darken-4">{{ data.weather }}<i
                                class="material-icons right">close</i></span>
    <div class="col s2">
      <img width="120%" src="{{ data.icon_url }}">

    </div>
    <div class="col push-s2">
      <p class="grey-text text-darken-4"><span class="card-title">Humid:</span> {{ data.humid }}</p>
      <p class="grey-text text-darken-4"><span class="card-title">WindChill:</span> {{ data.windchill }}</p>
      <p class=" grey-text text-darken-4"><span class="card-title">Wind:</span> {{ data.wind }}</p>
      <p class="" style="position: fixed;bottom: 0;width:100%;">{{ data.time }}</p>
    </div>
  </div>
</div>

templates/lab4/lab4.html
<!DOCTYPE html>
{% load static %}

<html ng-app="test">

<head>

  <meta name="viewport" content="width=device-width, initial-scale=1">

  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular-animate.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular-aria.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular-messages.min.js"></script>


  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
          integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
          crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
          integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
          crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'lab4:index' %}">Lab4</a></li>
        <li><a href="{% url 'lab1:index' %}">Lab1</a></li>
        <li><a href="{% url 'lab2:index' %}">Lab2</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'admin:index' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      </ul>
    </div>
  </div>
</nav>
<main>


  <div ng-controller="TestCtrl">
    {% verbatim %}
    <div class="container ">
      <div class="row">
        <div class="col-md-8 col-md-push-2 col-12">
          <div class="card text-center rounded align-self-center"
               style="border: 10px solid rgba(0,0,0,.125);border-radius: 10px;margin-top: 10%; padding: 10%;">
            <h1 class="card-header text-info" ng-bind="data['location']">
            </h1>
            <div class="card-block">
              <h4 class="card-title text-white">Current Weather</h4>
              <img ng-src="{{ data['icon_url']}}" src="">
              {{ data['temperature'] }}

              <h4 class="grey-text text-darken-4"><span class="card-title">Humid:</span>{{data['humid']}} </h4>
              <h4 class="grey-text text-darken-4"><span class="card-title">WindChill:</span> {{ data['windchill'] }}
              </h4>
              <h4 class=" grey-text text-darken-4"><span class="card-title">Wind:</span> {{ data['wind'] }}</h4>
              <a ng-href="{{data['forecast_url']}}" class="btn btn-primary">Forecast</a>
            </div>
            <div ng-bind="data['time']" class="card-footer text-muted">
            </div>
          </div>

        </div>

      </div>
    </div>
    {% endverbatim %}

  </div>
</main>
<script>

  var app = angular.module('test', []);
  app.controller('TestCtrl', function ($scope, $http) {
    $http.get("http://api.wunderground.com/api/3dfa9f9c19a712ac/conditions/q/CA/San_Francisco.json").then(function (res, status, xhr) {
      console.log('here1');
      var json_data = res.data;
      if ('current_observation' in json_data) {
        console.log('here2');
        $scope.get_data = true;
        $scope.data = {
          'location': json_data["current_observation"]["display_location"]["full"],
          'weather': json_data["current_observation"]["weather"],
          'windchill': json_data["current_observation"]['windchill_string'],
          'temperature': json_data["current_observation"]['temperature_string'],
          'time': json_data["current_observation"]["observation_time"],
          'wind': json_data["current_observation"]["wind_string"],
          'humid': json_data["current_observation"]["relative_humidity"],
          'icon_url': json_data["current_observation"]["icon_url"],
          'forecast_url': json_data["current_observation"]["forecast_url"]
        }

      }
    });
  });

</script>
</body>
</html>